baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Will Velida'
theme = 'ananke'

DefaultContentLanguage = 'en'
SectionPagesMenu = 'main'
Paginate = 9
googleAnalytics = ''
enableRobotsTXT = true

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "I code, I speak, I blog."
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-blue"
  recent_posts_number = 3

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/willvelida"