baseURL: 'http://example.org/'
title: 'Will Velida'
theme: 'PaperMod'

enableRobotsTXT: true

params:
    profileMode:
        enabled: true
        title: "Will Velida" # optional default will be site title
        subtitle: "I code, I blog, I speak"
        imageUrl: "https://pbs.twimg.com/profile_images/1391280978056806402/Y2FzLmYh_400x400.jpg" # optional
        imageTitle: "This is me" # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
        buttons:
          - name: Archive
            url: "/archive"
          - name: Github
            url: "https://github.com/"

    socialIcons: # optional
        - name: "github"
          url: "https://github.com/willvelida"
        - name: "twitter"
          url: "https://twitter.com/willvelida"