baseURL: 'https://www.willvelida.com/'
title: 'Will Velida'
theme: 'PaperMod'
paginate: 5

enableRobotsTXT: true
googleAnalytics: UA-91960027-1
enableEmoji: true

params:
  profileMode:
      enabled: true
      title: "Will Velida" # optional default will be site title
      subtitle: "I code, I blog, I speak"
      imageUrl: "https://avatars.githubusercontent.com/u/8111944?v=4" # optional
      imageTitle: "This is me" # optional
      imageWidth: 120 # custom size
      imageHeight: 120 # custom size
      buttons:
        - name: About Me
          url: "/about"
        - name: Blog
          url: "/posts"

  socialIcons: # optional
      - name: "github"
        url: "https://github.com/willvelida"
      - name: "youtube"
        url: "https://www.youtube.com/@willvelida"
      - name: "bluesky"
        url: "https://bsky.app/profile/willvelida.com"
      - name: "medium"
        url: "https://medium.com/@willvelida"
      - name: "dev"
        url: "https://dev.to/willvelida"
      - name: "twitter"
        url: "https://twitter.com/willvelida"
      - name: "linkedin"
        url: "https://www.linkedin.com/in/willvelida/"

  ShowShareButtons: true
  ShowReadingTime: true
  ShowPostNavLinks: true
  author: "Will Velida"
  env: production
  ShowCodeCopyButtons: true
  comments: true

outputs:
  home:
    - HTML 
    - RSS 
    - JSON

menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 10
    - identifier: blog
      name: Blog
      url: /posts/
      weight: 20
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 30